version: "3.1"

services:

  db:
    image: postgres:15.3-alpine
    restart: always
    environment:
      POSTGRES_DB: jwt_security
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    restart: always
#    environment:
#      POSTGRES_DB: university
#      POSTGRES_USER: myuser
#      POSTGRES_PASSWORD: mydatabase
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/database
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db